### ISSUE TITLE
Tests passing incorrectly

### ISSUE THREAD

**Issue by talldan** [bjornbytes/lust#2]
Hey - I spotted an issue that was introduced in this commit:
https://github.com/bjornbytes/lust/commit/df7f42f0e7c51b1f307cc4cb41a803d11298f6c2

Tests seem to incorrectly pass

I've taken the liberty of making a PR with a fix here:
https://github.com/bjornbytes/lust/pull/1

**Comment by bjornbytes** [comment]
Fixed by #1
