### ISSUE TITLE
Latest release (v0.1.0, on Dec 26, 2015) extremely outdated

### ISSUE THREAD

**Issue by inobelar** [bjornbytes/lust#7]
First of all - I want to thank you for this wonderful library!

I was looking for a small library for Lua testing, without dependencies (like [Catch2](https://github.com/catchorg/Catch2) or [doctest](https://github.com/doctest/doctest) for C++), first I found [busted](https://github.com/lunarmodules/busted) but its requires a lot of dependencies, so next I find this amazing gem!

At first I tried the [`latest release`](https://github.com/bjornbytes/lust/releases), but I was surprised that the fail tests pass **successfully** in it - even in example from README, `expect(nil).to.exist() -- Fail` **not** fails ! 0___o Next, I'm tried to use code from latest commit, and everything fixed :)

So, can you please remove `releases` at all - to not confuse anyone (like me, who will try to use `releases` first), or update `releases` time-to-time?

**Comment by bjornbytes** [comment]
I just published [v0.2.0](https://github.com/bjornbytes/lust/releases/tag/v0.2.0).  Thanks!
